/**
 * Candidate generator — dev-only maintainer tooling. NOT part of the shipped CLI.
 *
 * Runs the real pipeline over every recorded fixture under a golden root and
 * writes each produced `Analysis` to `<case>/expected.json.candidate`. The output
 * is a **starting point for a human review**, not ground truth. Task 9 exists
 * because a golden file generated by the code it is meant to check proves
 * nothing until a person has read it field by field against the recorded
 * response; this script only removes the transcription labour from that read.
 *
 * It lives under `scripts/` for the same two reasons `recordFixture.ts` does:
 * the Requirement 15 read-only AST guard scans `src/`, and the package `files`
 * allowlist names `bin/` and `dist/` only, so nothing here can ship by accident.
 *
 * ## What it does not do
 *
 * **No network calls, of any kind.** Unlike the recorder — which is the one
 * component allowed an unsolicited request — this script reads `input.json` off
 * disk and calls pure functions. There is no `fetch` here and no transitive path
 * to one: `FixtureSource` reads a file, and `analyzeTransaction` performs no I/O.
 * It is therefore safe to run with the network down, and it would pass the task
 * 1.3 interceptor if it were ever run under vitest.
 *
 * **No second definition of anything.** Three things are imported rather than
 * reimplemented, and each import is load-bearing:
 *
 * - `discoverFixtures` from the harness, so this script's idea of "a fixture"
 *   cannot drift from the suite's — including the code-point sort, which is
 *   deliberately not `localeCompare` (Req 9.7).
 * - `FixtureSource` from `src/`, so `input.json` is parsed by the production
 *   loader with its strict UTF-8 decode and its `asTransactionResponse` guard.
 *   A local `readFile` + `JSON.parse` would be a second parser, and a candidate
 *   generated through it would not be a statement about the parse the harness
 *   later compares against.
 * - `canonicalize` from the harness, so the candidate is in exactly the shape
 *   the harness compares with. This is what makes the candidate *usable*:
 *   renaming a reviewed candidate to `expected.json` must make the golden test
 *   pass with no further edits, and it can only be relied on to do that if one
 *   function defines canonical for both sides.
 *
 * ## Running it
 *
 * Same story as `recordFixture.ts` — a TypeScript file with no runner in
 * `devDependencies`. `tsx` is not installed, so this fetches it:
 *
 *   npx tsx scripts/generateCandidates.ts
 *
 * or, with nothing beyond what `npm install` already put in `node_modules`,
 * compile to a scratch directory with the installed compiler and run the output:
 *
 *   npx tsc -p tsconfig.json --noEmit false --outDir .candidates-out \
 *     --declaration false --sourceMap false
 *   node .candidates-out/scripts/generateCandidates.js
 *   rm -rf .candidates-out
 *
 * The `-p` matters, and is not interchangeable with naming this file on the
 * command line. Passing `tsc` a file path makes it ignore `tsconfig.json`
 * outright — including `strict` and the extra checks layered on top of it — and
 * the resulting unconfigured check reports around ten errors in `idlStore.ts`,
 * `fixture.ts`, and `harness.ts` that do not exist under the project config,
 * where `npx tsc --noEmit` is clean. Those errors are artefacts of the
 * invocation, not of the code; emit succeeds anyway, so the generated JS is the
 * same either way, but there is no way to tell that from the output. `-p` uses
 * the project config and the three overrides above turn its repo-wide `noEmit`
 * into a scratch-directory emit without a declaration or source-map step
 * nothing here reads.
 *
 * Flags:
 *
 *   --root <path>          Golden root to scan (default: tests/golden)
 *   --out-suffix <name>    Output file name written into each case directory
 *                          (default: expected.json.candidate)
 *
 * `--out-suffix` is a parameter rather than a literal at the write call for one
 * specific reason: once a human has actually reviewed a candidate, task 9 points
 * the same script at `expected.json` for that case and gets a byte-identical
 * file, instead of a maintainer hand-copying and hoping. It is not defaulted to
 * `expected.json`, because a default that overwrote ground truth would make an
 * accidental run silently destroy the thing the review produced.
 */

import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { argv, exit, stderr, stdout } from 'node:process';

import type { Base58Signature } from '../src/model/analysis.js';
import { analyzeTransaction } from '../src/pipeline.js';
import { FixtureSource } from '../src/source/fixture.js';
import type { TransactionSource } from '../src/source/index.js';
import {
  canonicalize,
  discoverFixtures,
  INPUT_FILE,
  type JsonValue,
} from '../tests/golden/harness.js';

/** Default golden root, matching `tests/golden/golden.test.ts`. */
const DEFAULT_ROOT = 'tests/golden';

/**
 * Default output name. Deliberately not `expected.json`: this script must never
 * be able to overwrite a hand-reviewed golden file by default.
 *
 * The `.candidate` extension also keeps the file invisible to fixture discovery,
 * which keys on being a directory — a candidate is a file inside a case
 * directory, so it is never mistaken for a case.
 */
const DEFAULT_OUT_SUFFIX = 'expected.json.candidate';

/**
 * The stem `FixtureSource` composes into `input.json`, exactly as the harness
 * does it. Typed as a `Base58Signature` because every character is in the base58
 * alphabet, so nothing about this path is a special case inside `FixtureSource`.
 */
const INPUT_STEM: Base58Signature = 'input';

/** Two-space indent and a trailing newline: a human has to read this. */
const INDENT = 2;

/** Generation failed in a way the maintainer needs to see, not a bug. */
class GeneratorError extends Error {}

// ---------------------------------------------------------------------------
// Options
// ---------------------------------------------------------------------------

export interface GenerateOptions {
  /** Golden root to scan for case directories. */
  readonly root: string;
  /** File name written into each case directory. */
  readonly outSuffix: string;
}

/**
 * Minimal `--flag value` parse, hand-rolled for the same reason the recorder's
 * is: this file never ships and the flag set is fixed.
 */
export function parseArgs(args: readonly string[]): GenerateOptions {
  const flags = new Map<string, string>();
  for (let i = 0; i < args.length; i += 1) {
    const arg = args[i];
    if (arg === undefined) continue;
    if (!arg.startsWith('--')) throw new GeneratorError(`unexpected argument: ${arg}`);
    const value = args[i + 1];
    if (value === undefined || value.startsWith('--')) {
      throw new GeneratorError(`missing value for ${arg}`);
    }
    flags.set(arg.slice(2), value);
    i += 1;
  }

  const outSuffix = flags.get('out-suffix') ?? DEFAULT_OUT_SUFFIX;
  // A path separator here would write outside the case directory, which is not
  // what "the name of the file in each case directory" means.
  if (outSuffix === '' || outSuffix.includes('/') || outSuffix.includes('\\')) {
    throw new GeneratorError(`--out-suffix must be a bare file name, got ${outSuffix}`);
  }

  return { root: flags.get('root') ?? DEFAULT_ROOT, outSuffix };
}

// ---------------------------------------------------------------------------
// Generation
// ---------------------------------------------------------------------------

/** What one case directory produced. */
export interface Candidate {
  readonly name: string;
  readonly path: string;
  /** Bytes written, UTF-8, trailing newline included. */
  readonly byteLength: number;
  /** Top-level keys of the canonical `Analysis`. */
  readonly topLevelKeys: number;
}

/**
 * The canonical document text for one fixture, without writing it.
 *
 * Separated from the write so the serialization is testable and so a failure to
 * load or analyze cannot leave a truncated file behind: nothing is written until
 * the whole document exists.
 */
export async function renderCandidate(root: string, name: string): Promise<string> {
  const dir = join(root, name);

  // Through the production loader, not a local readFile: strict UTF-8, JSON
  // parsing, and the `asTransactionResponse` guard are all production behaviour,
  // and the harness reaches this same code when it later compares.
  const source: TransactionSource = new FixtureSource(dir);
  const fetched = await source.fetch(INPUT_STEM);
  if (!fetched.ok) {
    const error = fetched.error;
    const detail =
      error.kind === 'fixture-unreadable' ? `${error.path}: ${error.detail}` : error.kind;
    throw new GeneratorError(`${name}: ${INPUT_FILE} could not be loaded (${detail})`);
  }

  // The real pipeline, with no IDL store — exactly how the harness runs it, so a
  // candidate reflects the resolution the suite will see rather than a richer one
  // a `--idl-dir` would have produced.
  const analysis = analyzeTransaction({ response: fetched.response, idls: null });
  const canonical: JsonValue = canonicalize(analysis);
  return `${JSON.stringify(canonical, null, INDENT)}\n`;
}

/** Number of top-level keys, or 0 for a document that is not an object. */
function topLevelKeyCount(document: string): number {
  const parsed: unknown = JSON.parse(document);
  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) return 0;
  return Object.keys(parsed).length;
}

/**
 * Generate one candidate per discovered case directory, in discovery order.
 *
 * A case that cannot be loaded or analyzed aborts the run rather than being
 * skipped, because a silently missing candidate is exactly the omission the
 * harness's `pending` outcome exists to make loud, and repeating that mistake
 * here would be perverse.
 */
export async function generateCandidates(
  options: GenerateOptions,
): Promise<readonly Candidate[]> {
  const candidates: Candidate[] = [];
  for (const name of await discoverFixtures(options.root)) {
    const document = await renderCandidate(options.root, name);
    const path = join(options.root, name, options.outSuffix);
    await writeFile(path, document, 'utf8');
    candidates.push({
      name,
      path,
      byteLength: Buffer.byteLength(document, 'utf8'),
      topLevelKeys: topLevelKeyCount(document),
    });
  }
  return candidates;
}

// ---------------------------------------------------------------------------
// CLI entry point
// ---------------------------------------------------------------------------

const USAGE = `Usage: generateCandidates.ts [options]

  --root <path>        Golden root to scan (default: ${DEFAULT_ROOT})
  --out-suffix <name>  File name written into each case directory
                       (default: ${DEFAULT_OUT_SUFFIX})

Writes one file per discovered case directory. Candidates are inputs to a human
review, not ground truth: nothing here has been read by a person yet.
`;

async function main(args: readonly string[]): Promise<number> {
  let options: GenerateOptions;
  try {
    options = parseArgs(args);
  } catch (error) {
    stderr.write(`generateCandidates: ${error instanceof Error ? error.message : String(error)}\n`);
    stderr.write(USAGE);
    return 2;
  }

  try {
    const candidates = await generateCandidates(options);
    for (const candidate of candidates) {
      stdout.write(
        `${candidate.name}  ${candidate.byteLength} bytes  ` +
          `${candidate.topLevelKeys} top-level keys  -> ${candidate.path}\n`,
      );
    }
    stdout.write(`${candidates.length} candidate(s) written under ${options.root}\n`);
    return 0;
  } catch (error) {
    stderr.write(`generateCandidates: ${error instanceof Error ? error.message : String(error)}\n`);
    return 1;
  }
}

// Runs only when this file is the process entry point, so importing it for the
// pure helpers never writes a file.
if (import.meta.url === `file://${argv[1] ?? ''}`) {
  exit(await main(argv.slice(2)));
}
